# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7e786e898cb87cbabac94f259f0398adc0c48d8aae2736197a3aa5446244c46a1c48eaf145617fb371d676a7b051a78953e5c78f256e61f4f8998e1f889c16c

test:
  secret_key_base: 67b9bee255f1e4aea013f883352aa5565644507daf1d1e34dfdbfac0675ebdb4b37a2730425fa3c170d4b20aae7f0c8fb86e7f80c2da8d4f0f2810c34604c3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
